[package]
name = "bouncyball"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = { version = "0.4.14", features = ["audio"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true